cost = {
    TOKEN_OPAREN: "TOKEN_OPAREN",
    TOKEN_CPAREN: "TOKEN_CPAREN",
    TOKEN_OCURLY: "TOKEN_OCURLY",
    TOKEN_CCURLY: "TOKEN_CCURLY",
    TOKEN_COMMA: "TOKEN_COMMA",
    TOKEN_SEMICOLON: "TOKEN_SEMICOLON",
    TOKEN_NUMBER: "TOKEN_NUMBER",
    TOKEN_STRING: "TOKEN_STRING",
    TOKEN_RETURN: "TOKEN_RETURN"
}